{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8304b755-3fca-4557-9e2e-f9ebfffc2de0",
   "metadata": {},
   "outputs": [],
   "source": [
    "import joblib\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import streamlit as st\n",
    "\n",
    "# ==============================\n",
    "# Load model and feature columns\n",
    "# ==============================\n",
    "model = joblib.load('best_model.pkl')\n",
    "feature_cols = joblib.load('best_model_columns.pkl')\n",
    "\n",
    "st.title(\"🌾 Crop Recommendation System\")\n",
    "st.write(\"Predict the most suitable crop based on environmental and soil conditions.\")\n",
    "\n",
    "# ==============================\n",
    "# Sidebar / Input Form\n",
    "# ==============================\n",
    "st.sidebar.header(\"Input Features\")\n",
    "\n",
    "region = st.sidebar.selectbox(\n",
    "    \"Region\",\n",
    "    [\"East\", \"West\", \"North\", \"South\", \"Borneo\"]\n",
    ")\n",
    "\n",
    "season = st.sidebar.selectbox(\n",
    "    \"Season\",\n",
    "    [\"Dry\", \"Wet\", \"Inter-monsoon\"]\n",
    ")\n",
    "\n",
    "rainfall = st.sidebar.number_input(\"Rainfall (mm)\", min_value=0.0, step=1.0, value=100.0)\n",
    "temperature = st.sidebar.number_input(\"Temperature (°C)\", min_value=0.0, step=0.1, value=28.0)\n",
    "humidity = st.sidebar.number_input(\"Humidity (%)\", min_value=0.0, max_value=100.0, step=1.0, value=70.0)\n",
    "soil_ph = st.sidebar.number_input(\"Soil pH\", min_value=0.0, max_value=14.0, step=0.1, value=6.5)\n",
    "\n",
    "if st.button(\"🔍 Predict Recommended Crop\"):\n",
    "    # Build raw input DataFrame\n",
    "    user_raw = pd.DataFrame([{\n",
    "        \"Region\": region,\n",
    "        \"Season\": season,\n",
    "        \"Rainfall_mm\": rainfall,\n",
    "        \"Temperature_C\": temperature,\n",
    "        \"Humidity_pct\": humidity,\n",
    "        \"Soil_pH\": soil_ph\n",
    "    }])\n",
    "\n",
    "    # One-hot encode Region & Season same as training\n",
    "    user_encoded = pd.get_dummies(user_raw, columns=['Region', 'Season'], drop_first=True)\n",
    "\n",
    "    # Align to training columns\n",
    "    user_encoded = user_encoded.reindex(columns=feature_cols, fill_value=0)\n",
    "\n",
    "    # Predict class\n",
    "    pred_crop = model.predict(user_encoded)[0]\n",
    "\n",
    "    # Predict probabilities for confidence score\n",
    "    if hasattr(model, \"predict_proba\"):\n",
    "        proba = model.predict_proba(user_encoded)[0]\n",
    "        confidence = float(np.max(proba))\n",
    "    else:\n",
    "        confidence = None\n",
    "\n",
    "    # --- Display results ---\n",
    "    st.subheader(\"Prediction Result\")\n",
    "    st.write(f\"**Recommended Crop:** `{pred_crop}`\")\n",
    "\n",
    "    if confidence is not None:\n",
    "        st.write(f\"**Confidence Score:** `{confidence:.2f}`\")\n",
    "\n",
    "    # --- Simple interpretation message ---\n",
    "    msg = \"\"\n",
    "\n",
    "    if pred_crop.lower() == \"rice\":\n",
    "        msg = \"Rice is suitable due to relatively higher rainfall and humidity conditions.\"\n",
    "    elif pred_crop.lower() == \"wheat\":\n",
    "        msg = \"Wheat is often suitable in cooler temperatures with moderate rainfall.\"\n",
    "    elif pred_crop.lower() in [\"corn\", \"maize\"]:\n",
    "        msg = \"Corn typically grows well in warm temperatures with moderate rainfall.\"\n",
    "    elif pred_crop.lower() == \"soybean\":\n",
    "        msg = \"Soybean prefers warm climates and well-drained soil with balanced pH.\"\n",
    "    else:\n",
    "        msg = \"This crop is suggested based on the current combination of climate and soil features.\"\n",
    "\n",
    "    st.info(msg)\n",
    "\n",
    "    # Optional: show the exact input back to user\n",
    "    st.markdown(\"### Your Input Data\")\n",
    "    st.write(user_raw)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
